GET http://localhost:8080
###
GET http://localhost:8080/info
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "test1",
  "cookingTime": 30,
  "ingredients": [
    {
      "title": "ingredient1",
      "number": 100,
      "measure": "gram"
    }
  ],
  "steps": [
    "step 1",
    "step 2",
    "step 3"
  ]
}
###
GET http://localhost:8080/recipe/0
###
POST http://localhost:8080/ingredient/create
Content-Type: application/json

{"title": "мука"
}
